sabre1041/managing-ocp-install-beyond

- openshift-infra/aws_create_hosts.yml
- openshift-infra/aws_lab_launch.yml
- openshift-infra/aws_vars.yml
- openshift-infra/my_secrets.yml
* Use lab_creator instead of lab_user
* Add stub secrets file to show example
To test this please edit your instance filter:
1. inventories
2. OpenShift
3. Edit AWS
4. Set instance filters to: tag:student_id=YOUR_STUDENT_ID_HERE
5. replace with the same student_id you will use in the next step
6. Test job template 1
You will also need to point to this branch for your Project instead of the one in the image
> Update AMI ID, move to us-east-2, minor tag tweaks

- openshift-infra/tower_config.yml
- openshift-infra/tower_vars.yml
Set
```
tower_config: true
tower_workflow_job_launch: true
```
watch playbook to end, give feedback
> Verify workflow job completed from Ansible playbook CLI

- openshift-infra/templates/OSEv3.yml.j2
username is now `student` with the same password as the other lab assets in this lab.
> Change ocp user password

- aws_vars.yml
To test set:
```
tower_config: false
```
Then ssh to Tower and test with:
```
tower-cli credential list
```
You should see the machine and cloud credentials.
> Update tower_ami_id to latest with tower-cli installed

- labs/lab5/chapter5.adoc
> Updates to lab 5

- labs/lab4/lab4.adoc
Clarified verification of successful CFME deployment based on lab feedback
> Clarified CFME deployment documentation

- aws_add_node.yml
- aws_create_hosts.yml
- aws_vars.yml
- roles/tower_config/defaults/main.yml
- roles/tower_config/tasks/inventory.yml
- roles/tower_config/tasks/inventory/groups.yml
- roles/tower_config/templates/OSEv3.yml.j2
- roles/tower_config/templates/tower_job_template_self_configure_extra_vars.yml.j2
- roles/tower_config/templates/tower_workflow_template_deploy_extra_vars.yml
- roles/tower_config/vars/full.yml
- roles/tower_config/vars/none.yml
- roles/tower_config/vars/self.yml
- roles/tower_config/vars/test.yml
Initial work to support new tower inventory convention
@scollier please review
> Initial work to support new tower inventory

- roles/tower_config/tasks/job_templates/deploy_install.yml
Associate cloud credential to deploy template
@scollier please review
> Adding cloud credential to deploy install template

- roles/ec2-security-key/tasks/main.yml
Dump AWS private key to PEM File
> Dump AWS private key to PEM File

- openshift_postinstall.yml
- roles/tower_config/templates/OSEv3.yml.j2
Remove non necessary commands in post installation and update OCP password
> Postinstall

- launch.sh
> Create launcher script

- launch.sh
Added default QUIET var value to enable checks by default.
> Add default QUIET value

- aws_vars.yml
Add default ssh key to configuration. 
Tested the change in phase 1 (creating VPC and key itself)
> Add default ssh key to configuration

- aws_vars.yml
- roles/tower_config/defaults/main.yml
- roles/tower_config/tasks/inventory/groups.yml
- roles/tower_config/tasks/job_templates/scaleup_install.yml
- roles/tower_config/tasks/job_templates/scaleup_provision.yml
- roles/tower_config/vars/full.yml
- roles/tower_config/vars/none.yml
- roles/tower_config/vars/self.yml
- roles/tower_config/vars/test.yml
Support for scaling up a cluster
@vvaldez @scollier 
Test with:
`tower_project_provision_and_configure_branch: "scaleup-fix"`
> Scaleup fix

- openshift_postinstall.yml
- roles/tower_config/templates/OSEv3.yml.j2
Adds support to communicate with node exporters and web console endpoints for Prometheus
> Updates for Prometheus

- alertmanager-tower-bridge/.s2i/bin/assemble
- alertmanager-tower-bridge/.s2i/bin/run
- alertmanager-tower-bridge/bridge.py
Application that will bridge webhook requests from AlertManager to Ansible Tower to trigger automation
> Sample application to bridge requests from AlertManager to Tower

- labs/prom-grafa.adoc
This PR is a WIP, but I'd like to get it merged in, then I will organize it into lab 5, and push lab 6,7,8 up one.  To test this PR, you just need a functioning OCP environment, and go through the doc here.
> WIP, initial commit of prometheus and grafana

- openshift_postinstall.yml
Restored PHP and MySQL ImageStreams
> Restored PHP and MySQL ImageStreams

- roles/tower_config/templates/OSEv3.yml.j2
Changing the admin password to match the student password
> Change admin password to match student password

- roles/tower_config/tasks/main.yml
To test, run with 'tower_cofig=test'
> Rearrange order of workflow job which affects 'tower_config=test'

- labs/lab0/lab0.adoc
- labs/lab1/lab1.adoc
- labs/lab2/lab2.adoc
- labs/lab3/lab3.adoc
- labs/lab4/lab4.adoc
- labs/lab5/lab5.adoc
> Fixes cross references between labs

- roles/tower_config/tasks/auth.yml
- roles/tower_config/tasks/main.yml
- roles/tower_config/tasks/openshift_auth.yml
Corrections to allow scaleup playbook to function properly
> Moving around OpenShift authentication

- labs/lab2/lab2.adoc
- labs/lab3/lab3.adoc
- labs/lab4/lab4.adoc
- labs/lab5/lab5.adoc
- labs/lab6/lab6.adoc
- labs/lab7/lab7.adoc
Updated CF deployment process and resolved syntax errors.
> Rhte2018 lab updates

- labs/lab2/lab2.adoc
* Spelling correction
* Remove extraneous 'by' in sentence
> Lab2 - Minor edits

- labs/lab4/lab4.adoc
* Fix sentence segment: 'to see how to these'
* Correct: it's -> its
> Lab4 - Minor edits
