sabre1041/managing-ocp-install-beyond

openshift-infra/templates/tower_workflow_template_extra_vars.yml, openshift-infra/tower_config.yml, openshift-infra/tower_vars.yml
* Also adds variable tower_workflow_job_launch to launch workflow at end
of tower config
* Clean up extra_vars for workflow
* Add openshift_cluster_public_url to workflow for students to access
To test set `tower_config: true` and run. The result should be a fully configured Tower that kicks off the OCP Install job template. (Optionally set `tower_workflow_job_launch` to False in you vars file if desired and the workflow job will not run automatically).
Next, login to Tower and click *Jobs* and verify the workflow and job are running. Under Workflow, verify there is a variable `openshift_cluster_public_url`, this should open the OCP console once installed.
Optionally try setting `student_count` to something higher than 1 and ensure all the clusters come up.
=> Correct accidental tower_config even when false

openshift-infra/aws_vars.yml, openshift-infra/aws_vpc_keypair.yml, openshift-infra/roles/ec2-security-key/tasks/main.yml, openshift-infra/roles/vpc/tasks/main.yml
To test this out:
- Swap over to Nicks new AWS environment.
-- Access us-east-2 region, confirm there is not an existing VPC with the name RHTE-APAC, nor a keypair, nor a security group.
- Add the following variables to your secrets file:
```
aws_vpc_name: RHTE-APAC-VPC
aws_vpc_cidr_block: 10.10.0.0/16
aws_subnet_cidr: 10.10.0.0/24
aws_subnet_name: "RHTE APAC Public Subnet"
aws_route_table: "RHTE APAC Public"
aws_sec_grp: "RHTE APAC Security Group"
aws_sec_grp_desc: "RHTE APAC Security Group"
```
- Run the playbook
ansible-playbook -vvv aws_vpc_keypair.yml  -e @<your-name>_secrets.yml
- Go back to AWS console, you should now see VPC, keypair and security group.  On the VPC, you MUST enable auto-assign IPs on the subnet.  Find the subnet with the RHTE-* name and right click on it and …
=> adding ability to set up AWS VPC, keypair, sec groups for new regions

openshift-infra/aws_vars.yml, openshift-infra/roles/vpc/tasks/main.yml
This PR sets the `aws_vars.yml` variables for the new APAC environment. Running `aws_vpc_keypair.yml` with this PR should not change anything as the objects are already there. Running `aws_lab_launch.yml` will not work until the AMIs are copied over and updated.
=> Change region info to new APAC region

openshift-infra/openshift_postinstall.yml, openshift-infra/templates/OSEv3.yml.j2
Steps to deploy and enable the service catalog and ansible-service broker.
* Deploy a new instance of Tower
* Navigate to _Projects_ and edit the _Managing OCP from Install and Beyond_ project
** Set the branch to **service-catalog-and-postinstall**
* Run the **1-Deploy_OpenShift_on_AWS** Workflow Job Template
* Verify Service Catalog UI now present in OpenShift Web Console
* Verify all pods are running in the _kube-service-catalog_ project
* Verify _defaultNodeSelector_ in _/etc/origin/master/master-config.yaml_ is set to **type=app**
=> Service catalog and postinstall

openshift-infra/aws_lab_launch.yml
To test, set the following variables:
```
tower_config: false
student_count: 2 # or any higher number
```
- Check AWS route53 entries before and after running `aws_lab_lanunch.yml` to verify all tower entries are created.
=> Corret route53 loop to properly create entries for tower instances

openshift-infra/aws_vars.yml, openshift-infra/tower_config.yml, openshift-infra/tower_vars.yml
This PR updates the Tower AMI to `tower_ami_id_unconfigured: ami-fee98b9d` which contains the following fix:
The Tower AMI now has the repo for OCP 3.6 enabled, and `openshift-ansible-playbooks` installed.
I've also modified `/usr/share/ansible/openshift-ansible/roles/openshift_node_certificates/tasks/main.yml` and added the following at line 52:
```
- name: Check if ca-bundle.crt exists on openshift_ca_host
stat:
path: /etc/origin/master/ca-bundle.crt
register: ca_bundle_cert_stat_result
delegate_to: "{{ openshift_ca_host }}"
run_once: true
- name: Overwrite cat.crt with ca-bundle.crt per github issue 4442
shell: "cat /etc/origin/master/ca-bundle.crt > /etc/origin/master/ca.crt"
delegate_to: "{{ openshift_ca_host }}"
when: ca_bundle_cert_stat_result.stat.exists | bool
run_once: true
``` …
=> Update tower ami with fixed scaleup

labs/lab1/chapter1.adoc, labs/lab6/chapter6.adoc, templates/OSEv3.yml.j2
This PR changes the OCP user from `student` to the dynamic value of `<student_id>`. 
To test, set these variables:
```
tower_config: true
tower_workflow_job_deploy_launch: true
```
Without waiting for the full OCP install, you can login to Tower and edit the `OSEv3` inventory and verify the user is set in the variables section.
Once OCP install is finished, ensure the `<student_id>` can login.
=> Replace OCP user to be the unique <student_id>

roles/tower_config/tasks/inventory/groups.yml
Addresses #99 
To test run `aws_lab_launch.yml` with these variables:
```
tower_password: "password"
tower_config: true
tower_config_type: self
tower_project_provision_and_configure_url: "https://github.com/vvaldez/summit-2017-ocp-operator.git"
tower_project_provision_and_configure_branch: "fix-inventory-source-region"
```
Go to `Inventories` then edit `AWS` and verify the `Regions` value is populated.
Optionally, to re-create the original issue create a Tower instance with one `student_id` in one region, then attempt to deploy with either `self`, `full` or `test` in another region with the same `student_id`.
=> Fix missing source region for AWS inventory in Tower

aws_vars.yml, my_secrets.yml
To enable multi-region support, we must have AWS location information in our secrets file, and not defaulted to in the main aws_vars.yml file
Your secrets fill will look something like this:
```
tower_password: "<CURRENT PASSWORD>"
tower_config: true
tower_config_type: self
lab_user: scollier-test
student_count: 2
#student_count_start: 4
#student_count_end: 6
aws_vpc_name: "RHTE-emea-VPC"
aws_subnet_id: "subnet-e4XXXXX98f"
aws_region: "eu-central-1"
aws_sec_group: "rhte-emea-security-group"
aws_vpc_name: "RHTE-emea-VPC"
aws_vpc_cidr_block: "10.30.0.0/16"
aws_subnet_cidr: "10.30.0.0/24"
aws_subnet_name: "RHTE EMEA Public Subnet"
aws_route_table: "RHTE EMEA Public"
tower_ami_id: ami-0167d06e
ocp_ami_id: ami-4267d02d
```
=> Become more AWS region agnostic

roles/tower_config/defaults/main.yml
Fixes error from previous refactor PR #102 by adding `aws_region`.
To test, deploy and environment then execute the terminate workflow job template.
=> Add aws_region to terminate playbook

labs/lab0/lab0.adoc, labs/lab1/lab1.adoc, labs/lab2/lab2.adoc
Minor updates including username from admin to <student_id> and removing sudo from `tower-cli` commands since auth is only saved for `ec2-user` and not `root`.
=> Update Tower username and other minor doc updates

aws_vars.yml, roles/tower_config/tasks/auth.yml, roles/tower_config/tasks/inventory.yml, roles/tower_config/tasks/inventory/groups.yml, roles/tower_config/tasks/job_templates/deploy_provision.yml, roles/tower_config/tasks/prereqs.yml, roles/tower_config/tasks/projects/install.yml, roles/tower_config/tasks/projects/provision_and_configure.yml, roles/tower_config/tasks/user.yml, roles/tower_config/vars/full.yml
There were a few ansible module to tower-cli conversions.  Nothing changes when testing this. It will provision a tower host, configure it properly. The next thing to work on is proper deployment of OCP 3.7.
=> This PR updates of Tower from 3.1.4 to 3.2.2

aws_vars.yml
Due to processes running out of memory, Tower instance type changed to t2.large
=> Tower instance t2.large

roles/tower_config/tasks/admin_password.yml, roles/tower_config/tasks/inventory.yml, roles/tower_config/tasks/main.yml, roles/tower_config/tasks/prereqs.yml
Changes inventory_source task to first check if one exists, if so it will modify it to add the correct filter. Otherwise it creates it as before.
Also added admin password change to whatever `tower_password` is being set to. However, this requires `pexpect` version 3.3 or higher. The rpm in RHEL repos is 2.3, so using pip to install it for this role, since we already have EPEL. These tasks will be ported over to the AAB soon. To test, set `tower_prereqs_config: true` and specify `tower_password:`
=> Fix filter tasks and add admin password change

aws_vars.yml, roles/tower_config/defaults/main.yml, roles/tower_config/files/deploy_cluster_wrapper.yml, roles/tower_config/tasks/job_templates.yml, roles/tower_config/tasks/job_templates/deploy_prerequisites.yml, roles/tower_config/tasks/job_templates/self_configure.yml, roles/tower_config/tasks/projects/install.yml, roles/tower_config/templates/OSEv3.yml.j2, roles/tower_config/templates/tower_job_template_self_configure_extra_vars.yml.j2, roles/tower_config/templates/tower_workflow_template_deploy_schema.yml, roles/tower_config/vars/full.yml, roles/tower_config/vars/none.yml, roles/tower_config/vars/self.yml, roles/tower_config/vars/test.yml
How to test this PR:
1. Deploy the lab by running the `aws_lab_launch.yml` playboook
2. Correct the Project to reference the PR branch
1. Select Projects -> Click _edit_ button next to "Managing OCP from Install and Beyond"
2. Change repository and branch to the following
* Repository: https://github.com/sabre1041/managing-ocp-install-beyond
* Branch: 3.9-updates
3. Check "Delete on Update"
4. Click Save
3. Execute the `Self Configure` Job Template
4. Enable `local_action` to escalate to sudo (Does not need to be completed once new AMI is spun)
1. Add the following to the `/etc/tower/settings.py` file
```
AWX_PROOT_ENABLED=False
```
2. Restart Tower
```
AWX_PROOT_ENABLED=False
```
3. Add the `awx` user to sudo up without a password by uncommenting the following line using `visudo`
``` …
```
=> Updates to Support OpenShift 3.9

aws_add_node.yml, aws_create_hosts.yml, aws_vars.yml, openshift_scaleup_postinstall.yml, roles/tower_config/defaults/main.yml, roles/tower_config/tasks/job_templates/scaleup_configure.yml, roles/tower_config/templates/tower_job_template_scaleup_postinstall_extra_vars.yml.j2, roles/tower_config/templates/tower_job_template_scaleup_provision_extra_vars.yml.j2
Added support for dynamically scaling up beyond 2 total dedicated nodes.
* Nodes now have a random 5 characters id value
* Support for managing tag names and Ansible Tower inventory
_Note_: This has yet to be tested E2E. PR being submitted to get eyes on it and for those interested to test it out. YMMV!
=> Support for dynamic scaleup

roles/tower_config/defaults/main.yml, roles/tower_config/vars/full.yml, roles/tower_config/vars/self.yml, roles/tower_config/vars/test.yml
* Set defaults/main.yml to false for these vars
* Set all profile vars to false too
* Override these vars to configure them
My command I used to test:
`ansible-playbook -e @vvaldez-secrets.yml aws_lab_launch.yml -e tower_ami_id=ami-XYZ`
=> Set credential config for machine and cloud to false by default

aws_vars.yml, roles/tower_config/defaults/main.yml
* Specify variable 'tower_credential_machine_ssh_key_data_file' in secrets
* Specify variables 'tower_ec2_access_key' and 'tower_ec2_secret_key'
=> Add tower ec2 variables and remove private key default filename

letsencrypt.yml, roles/letsencrypt/defaults/main.yml, roles/letsencrypt/tasks/assign_certificate.yml, roles/letsencrypt/tasks/generate_certificate.yml, roles/letsencrypt/tasks/main.yml, roles/tower_config/defaults/main.yml, roles/tower_config/tasks/inventory/groups.yml, roles/tower_config/tasks/letsencrypt.yml, roles/tower_config/tasks/main.yml, roles/tower_config/tasks/openshift_configs.yml, roles/tower_config/templates/OSEv3.yml.j2, roles/tower_config/vars/full.yml, roles/tower_config/vars/none.yml, roles/tower_config/vars/self.yml, roles/tower_config/vars/test.yml
Integration for Letsencrypt
There are two components of this integration that can be executed at different points as necessary
1. Generation of certificates from letsencrypt
2. Configuration of certificates as part of the lab launch
Test using the following steps:
1. Generate certificates by running the `letsencrypt.yml` playbook
```
ansible-playbook letsencrypt.yml -e @<summit_secrets_file>
```
1. New certificates should be generated in the `/tmp/letsencrypt` directory
2. Launch the lab
1. Add the following variable to enable SSL configuration in your secrets file
```
tower_ssl_config: true
```
2. Launch the lab and OpenShift as per usual 
3.  Tower, OpenShift Master and Wildcard Certificates will use letsencrypt SSL certificates. 
NOTE: By default, certificates are generated against the …
=> Letsencrypt implementation

tower_config.yml
* Now if you set 'tower_config: none' the role will not be called
* This should also be true if you do not define 'tower_config'
* For now all 'none' tasks remain in case role is used stand alone, but may be removed in the future
To test, call `aws_lab_launch.yml` as normal, but set `-e tower_config=none` as such:
```
ansible-playbook aws_lab_launch.yml -e @vvaldez-secrets.yml -e tower_ami_id=ami-a4d2c0c4 -e ocp_ami_id=ami-b33022d3 -e tower_config=none
```
After the Tower VM is instantiated, the playbook should stop with the following, since it should skip the tower_config role:
```
PLAY [Include tower_config role] *************************************************************************************************
TASK [Gathering Facts] …
```
=> Refactor the way tower_config role is called

aws_add_node.yml, aws_create_hosts.yml, aws_vars.yml, openshift_postinstall.yml, roles/tower_config/files/prometheus_additional_rule.yml, roles/tower_config/tasks/prereqs.yml, roles/tower_config/templates/OSEv3.yml.j2, roles/tower_config/templates/tower_workflow_template_deploy_extra_vars.yml, templates/aws_user_data.j2
Updates to support OCP 3.10
* Had to remove setting hostname for instances
* Updated the password for OpenShift
* Removed some items that  required customizations for features that did not work in prior versions
* Updated inventory
* Verified Lab launch, OCP launch, OCP scaleup
=> Support for OpenShift 3.10

my_secrets.yml, roles/tower_config/defaults/main.yml, roles/tower_config/tasks/auth.yml, roles/tower_config/templates/OSEv3.yml.j2, roles/tower_config/templates/tower_job_template_self_configure_extra_vars.yml.j2
Generates OpenShift password
To Test:
Add the following in your secrets file
```
ocp_password: <password>
```
To Validate
1. Run Lab Launch to deploy tower
2. Launch Self-Configure Job Template
3. Verify _htpasswd_ based password generated in the `OSEv3` OpenShift inventory group.
=> Adding logic to generate OpenShift password

roles/tower_config/templates/tower_workflow_template_deploy_schema.yml
remove prereq job template from workflow. job template is still created, but not executed.
=> Remove prereq job from workflow
